// backend/services/ai.quiz.service.js
const { GoogleGenerativeAI } = require('@google/generative-ai');

// Initialize with your API key from environment variable
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

const QUIZ_SCHEMA = {
    type: "object",
    properties: {
        title: { 
            type: "string", 
            description: "A concise, descriptive title for the quiz." 
        },
        courseName: { 
            type: "string" 
        },
        questions: {
            type: "array",
            description: "A list of 5 quiz questions.",
            items: {
                type: "object",
                properties: {
                    id: { 
                        type: "number", 
                        description: "Unique ID for the question (1, 2, 3...)." 
                    },
                    questionText: { 
                        type: "string", 
                        description: "The question text." 
                    },
                    type: { 
                        type: "string", 
                        enum: ["MCQ", "TrueFalse", "ShortAnswer"],
                        description: "Question type"
                    },
                    options: { 
                        type: "array", 
                        items: { type: "string" }, 
                        description: "4 possible choices for MCQ, empty for others." 
                    },
                    correctAnswer: { 
                        type: "string", 
                        description: "The single correct answer text." 
                    },
                    topic: { 
                        type: "string", 
                        description: "The topic the question tests." 
                    },
                    difficulty: { 
                        type: "string", 
                        enum: ["Easy", "Medium", "Hard"],
                        description: "Question difficulty level"
                    },
                },
                required: ["id", "questionText", "type", "correctAnswer", "topic", "difficulty"]
            }
        }
    },
    required: ["title", "courseName", "questions"]
};

async function generateQuizFromTopics(courseName, topics, difficulty = 'Mixed') {
    // Format topics list
    const topicsList = topics.map(t => {
        const topicName = typeof t === 'string' ? t : t.topic;
        const topicDiff = typeof t === 'object' && t.difficulty ? t.difficulty : 'Medium';
        return `${topicName} (Difficulty: ${topicDiff})`;
    }).join('; ');
    
    const systemPrompt = `You are a test creation expert. Generate a comprehensive 5-question quiz for ${courseName}. 
    
    Requirements:
    - Create exactly 5 questions
    - Use a mix of MCQ (3 questions), True/False (1 question), and Short Answer (1 question)
    - For MCQ questions, provide exactly 4 options (A, B, C, D format)
    - All questions must have a clearly defined correct answer
    - Make questions relevant to the course material
    - Vary difficulty levels appropriately
    
    Output must be valid JSON matching the schema.`;
    
    const userPrompt = `Generate a 5-question quiz for the course "${courseName}". 
    
    Focus on these topics: ${topicsList}
    
    Make sure:
    1. Questions test understanding of key concepts
    2. MCQ options are distinct and plausible
    3. Correct answers are clearly defined
    4. Questions are appropriate for exam preparation`;

    try {
        const model = genAI.getGenerativeModel({ 
            model: 'gemini-1.5-flash',
            generationConfig: {
                responseMimeType: "application/json",
                temperature: 0.7,
            }
        });

        const result = await model.generateContent([
            { text: systemPrompt },
            { text: userPrompt }
        ]);

        const response = await result.response;
        const jsonString = response.text();
        
        console.log('AI Response received, parsing...');
        
        const quizData = JSON.parse(jsonString);

        // Validate and format the response
        if (!quizData.questions || quizData.questions.length === 0) {
            throw new Error('No questions generated by AI');
        }

        // Ensure all questions have required fields
        quizData.questions = quizData.questions.map((q, index) => {
            // Ensure id is set
            if (!q.id) q.id = index + 1;
            
            // Ensure type is valid
            if (!['MCQ', 'TrueFalse', 'ShortAnswer'].includes(q.type)) {
                q.type = 'MCQ';
            }
            
            // For MCQ, ensure 4 options exist
            if (q.type === 'MCQ' && (!q.options || q.options.length < 4)) {
                q.options = ['Option A', 'Option B', 'Option C', 'Option D'];
            }
            
            // Ensure other types have empty options array
            if (q.type !== 'MCQ') {
                q.options = [];
            }
            
            // Ensure difficulty is set
            if (!q.difficulty) {
                q.difficulty = 'Medium';
            }
            
            // Ensure topic is set
            if (!q.topic) {
                q.topic = courseName;
            }
            
            return q;
        });

        quizData.courseName = courseName;
        quizData.title = quizData.title || `${courseName} Quiz`;

        console.log('Quiz generated successfully:', quizData.questions.length, 'questions');

        return quizData;

    } catch (error) {
        console.error('Gemini Quiz Generation Failed:', error);
        
        // Return a fallback quiz if AI fails
        console.log('Returning fallback quiz...');
        return {
            title: `${courseName} Practice Quiz`,
            courseName: courseName,
            questions: [
                {
                    id: 1,
                    questionText: `What is a key concept in ${courseName}?`,
                    type: 'MCQ',
                    options: ['Concept A', 'Concept B', 'Concept C', 'Concept D'],
                    correctAnswer: 'Concept A',
                    topic: courseName,
                    difficulty: 'Medium'
                },
                {
                    id: 2,
                    questionText: `${courseName} is fundamental to computer science.`,
                    type: 'TrueFalse',
                    options: [],
                    correctAnswer: 'True',
                    topic: courseName,
                    difficulty: 'Easy'
                },
                {
                    id: 3,
                    questionText: `Explain the main principles of ${courseName}.`,
                    type: 'ShortAnswer',
                    options: [],
                    correctAnswer: 'Student should explain key principles and concepts.',
                    topic: courseName,
                    difficulty: 'Medium'
                },
                {
                    id: 4,
                    questionText: `Which of the following is NOT related to ${courseName}?`,
                    type: 'MCQ',
                    options: ['Related Concept A', 'Related Concept B', 'Unrelated Concept', 'Related Concept C'],
                    correctAnswer: 'Unrelated Concept',
                    topic: courseName,
                    difficulty: 'Medium'
                },
                {
                    id: 5,
                    questionText: `What is the primary application of ${courseName}?`,
                    type: 'MCQ',
                    options: ['Application A', 'Application B', 'Application C', 'Application D'],
                    correctAnswer: 'Application A',
                    topic: courseName,
                    difficulty: 'Hard'
                }
            ]
        };
    }
}

module.exports = {
    generateQuizFromTopics,
};